# Generated by Django 5.2.4 on 2025-08-08 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookingsystemapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='is_popular',
            field=models.BooleanField(default=False),
        ),
    ]
