# Generated by Django 5.2.4 on 2025-08-08 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookingsystemapp', '0003_city_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='min_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
