# Generated by Django 5.2.4 on 2025-08-09 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookingsystemapp', '0004_city_min_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='guests',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
