# Generated by Django 5.2.4 on 2025-08-09 11:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookingsystemapp', '0005_place_guests'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='place',
            name='guests',
        ),
    ]
