# Generated by Django 5.2.4 on 2025-08-09 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookingsystemapp', '0006_remove_place_guests'),
    ]

    operations = [
        migrations.RenameField(
            model_name='place',
            old_name='price_per_hour',
            new_name='price_per_day',
        ),
    ]
