# Generated by Django 5.2.4 on 2025-08-23 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookingsystemapp', '0007_rename_price_per_hour_place_price_per_day'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='token',
            field=models.CharField(default='', max_length=16),
            preserve_default=False,
        ),
    ]
